version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sense-game-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sensegame
      - SPRING_DATASOURCE_USERNAME=sense_username
      - SPRING_DATASOURCE_PASSWORD=sense_password
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: sense-game-db
    environment:
      POSTGRES_USER: sense_username
      POSTGRES_PASSWORD: sense_password
      POSTGRES_DB: sensegame
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
