version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sense-game-db
    environment:
      POSTGRES_USER: sense_username
      POSTGRES_PASSWORD: sense_password
      POSTGRES_DB: sensegame
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  db-data:

networks:
  app-network:
