input {
  file {
    path => "/sense-game/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs"
  }
  stdout { codec => rubydebug }
}
